### ISSUE TITLE
Improve documentation on how to contribute to CL

### ISSUE THREAD

**Issue by lubianat** [obophenotype/cell-ontology#1288]
Currently the contributing session is largely empty. I'll try to add some information there: https://obophenotype.github.io/cell-ontology/contributing.html

**Comment by lubianat** [comment]
@shawntanzk any update on that?

**Comment by shawntanzk** [comment]
ODK has been updated - does it need a release to update @matentzn?

**Comment by matentzn** [comment]
Yeah, try to run an `update_repo` workflow and make sure to run it twice.

you should see a new file appearing: `.github/WORKFLOWS/docs.yml`. Once that is there, you should be able to run it by clicking on the action tab, selecting the docs action at hit "run workflow". For the next ODK version, we have implemented it so that it auto-deploys.

**Comment by lubianat** [comment]
@matentzn and @shawntanzk just an update, the documentation is still not deployed (https://obophenotype.github.io/cell-ontology/contributing.html). No rush, just thought to let you know.

**Comment by matentzn** [comment]
@shawntanzk let me know if you have an issue, should  be 5 min.

**Comment by anitacaron** [comment]
Now it's deployed

**Comment by lubianat** [comment]
It doesn't seem to be fixed: https://obophenotype.github.io/cell-ontology/contributing.html is still not deployed. @anitacaron do you know what might have happened?

**Comment by matentzn** [comment]
Wrong URL: https://obophenotype.github.io/cell-ontology/contributing/

**Comment by lubianat** [comment]
oops, thanks!

The https://obophenotype.github.io/cell-ontology/cite/  and https://obophenotype.github.io/cell-ontology/history/ are empty still though, but I guess this is just in need of documentation.
